### ISSUE TITLE
Set Filename automatically to the name of the selected Mesh/Object

### ISSUE THREAD

**Issue by MeerrettichMeister** [Road-hog123/Blender-OMSI-Exporter#3] opened 2022-02-20 14:33 UTC
## The problem
Currently you have to name the o3d by hand but it would be much faster and easier if the default name would be the name of the selected object. 

## The solution
using the bpy.context.active_object.name for the name instead of untitled.o3d/the last exportet name

**Comment by Road-hog123** [comment] 2022-02-20 16:49
Duplicate of #2

**Closed as completed by Road-hog123** 2022-02-20 16:49 UTC
Labels: enhancement
